config/routes.rb
Rails.application.routes.draw do

  resources :posts

  get 'about' => 'pages#about'

  root 'pages#welcome'

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def welcome
  	@posts=Post.all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  def index
    @posts = Post.all
  end

  # GET /posts/1
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post, notice: 'Post was successfully created.'
    else
      render :new
    end
    
  end

  # PATCH/PUT /posts/1
  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /posts/1
  def destroy
    @post.destroy
      redirect_to posts_url, notice: 'Post was successfully destroyed.'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content)
    end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Angelo Fu</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

    <!-- Latest compiled and minified CSS for Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

	  <%= csrf_meta_tags %>
	</head>
	<body>
    <div class="container">

      <div class="page-header">
        
        <ul class="nav nav-pills pull-right">
          <li><%= link_to "Home", root_path %>
          <li><%= link_to "About", about_path %>
          <li><%= link_to "Manage posts", posts_path %>
        </ul>

        <h1><%= link_to "Angelo Fu", root_path%><small> // this is a project by Angelo Fu</small></h1>

      </div>
      
      <div class="row">  

        <div class="col-md-6 col-md-offset-3">
    		  <%= yield %>
        </div>
      </div>

    </div>
	</body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>
<p>
	This is an <%= link_to "about page.", "http://www.angelofu.com/about" %>
</p>

app/views/pages/welcome.html.erb
<h1>This is Angelo's blog</h1>
<br></br><br></br>

<% @posts.each do |post| %>
  <%= render 'posts/post', post: post %>
  <br></br><br></br>
<% end %>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= f.label :content %><br>
    <%= f.text_area :content, class: 'form-control'%>
  </div>
  
  <div class="form-group">
    <%= f.submit "Create Post", class: "btn btn-primary"%>
  </div>
<% end %>

app/views/posts/_post.html.erb
<h2>
  <%= link_to post.title, post %>
</h2>

<p>
  <%= simple_format post.content %>
</p>

<p class="text-muted">
	<small>
		<%= post.created_at.to_formatted_s(:long) %>
	</small>
</p>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= truncate post.content, length: 140 %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<% if notice.present? %>
	<p class="alert alert-info"><%= notice %></p>
<% end %>


<%= render 'post', post: @post %>